# Generated by Django 3.2.6 on 2021-08-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='category_name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(default='condition_name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='product_name', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_minimum_order', models.IntegerField()),
                ('product_description', models.TextField()),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('product_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condition')),
            ],
        ),
    ]
